# Generated by Django 4.1.5 on 2024-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0041_stock_detail_after_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcr_values',
            name='live_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
